### ISSUE TITLE
'--style-file' gives java.lang.StackOverflowError

### ISSUE THREAD

**Issue by eludias** [maning/osmphgps#49]
I'm trying to use a different style then the built-in one. Running (r2277):

```
java -ea -Xmx4000m -classpath mkgmap/dist -jar mkgmap/dist/mkgmap.jar --style-file=mkgmap/resources/styles/default --list-styles
```

gives:

```
The following styles are available:
Exception in thread "main" java.lang.StackOverflowError
        at sun.nio.cs.UTF_8.updatePositions(UTF_8.java:58)
        at sun.nio.cs.UTF_8$Encoder.encodeArrayLoop(UTF_8.java:392)
        at sun.nio.cs.UTF_8$Encoder.encodeLoop(UTF_8.java:447)
        at java.nio.charset.CharsetEncoder.encode(CharsetEncoder.java:544)
        at java.lang.StringCoding$StringEncoder.encode(StringCoding.java:240)
        at java.lang.StringCoding.encode(StringCoding.java:272)
        at java.lang.String.getBytes(String.java:946)
        at java.io.UnixFileSystem.getBooleanAttributes0(Native Method)
        at java.io.UnixFileSystem.getBooleanAttributes(UnixFileSystem.java:228)
        at java.io.File.isDirectory(File.java:754)
        at uk.me.parabola.mkgmap.osmstyle.DirectoryFileLoader.<init>(DirectoryFileLoader.java:47)
        at uk.me.parabola.mkgmap.osmstyle.StyleFileLoader.createStyleLoader(StyleFileLoader.java:64)
        at uk.me.parabola.mkgmap.osmstyle.StyleImpl.<init>(StyleImpl.java:132)
        at uk.me.parabola.mkgmap.osmstyle.StyleImpl.readBaseStyle(StyleImpl.java:518)
        at uk.me.parabola.mkgmap.osmstyle.StyleImpl.<init>(StyleImpl.java:140)
        at uk.me.parabola.mkgmap.osmstyle.StyleImpl.readBaseStyle(StyleImpl.java:518)
...
```

**Comment by maning** [comment]
AFAIK, you cannot use two different style in a single map compile.

**Comment by eludias** [comment]
This is not about using two different styles; it is about an exception (which should never occur), and (in hindsight) unclear documentation. I thought that --style-file should point to the directory with the style, but it seems that --style-file should point to a directory of directory with styles, and that you must use --style to select a directory within the --style-file directory.

So the following now works:

```
java -ea -Xmx4000m -classpath mkgmap/dist -jar mkgmap/dist/mkgmap.jar --style-file=mkgmap/resources/styles --style=default --list-styles
```
